name: tic_tac_toe
description: A tic-tac-toe game built on the principles of clean architecture.
version: 1.0.0+1
publish_to: none

######

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^7.0.0
  flutter_bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

######

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Italic.ttf
          style: italic
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-BoldItalic.ttf
          weight: 700
          style: italic
